---

var_ansible_ssh_port: "{{ lookup('env', 'VAR_ANSIBLE_SSH_PORT') }}"
var_ansible_become_user: root
var_ansible_user_name: "{{ lookup('env', 'VAR_ANSIBLE_USER_NAME') }}"
var_ansible_user_pwd: "{{ lookup('env', 'VAR_ANSIBLE_USER_PASSWORD') }}"
var_ansible_user_pwd_hash: "{{ lookup('env', 'VAR_ANSIBLE_USER_PASSWORD') }}"
var_ansible_user_group: "{{ lookup('env', 'VAR_ANSIBLE_USER_GROUP') }}"
var_ansible_ssh_key_name: "{{ lookup('env', 'SSH_KEY_NAME') }}"
var_ansible_ssh_key_pri_path: "{{ '/root/.ssh/' ~ var_ansible_ssh_key_name ~ '.ansible_executer.id_rsa' }}"
var_ansible_ssh_key_pub_path: "{{ var_ansible_ssh_key_pri_path ~ '.pub' }}"
